name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        run: |
          echo "TAG_NAME=$(date +%Y.%m.%d.%H.%M)" >> "$GITHUB_ENV"
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}
      - name: Generate Autograder
        run: |
          make -C autograder
          mv autograder/build/autograder_lab1.zip autograder_lab1_${{ env.TAG_NAME }}.zip
          mv autograder/build/autograder_lab2.zip autograder_lab2_${{ env.TAG_NAME }}.zip
          mv autograder/build/autograder_lab3.zip autograder_lab3_${{ env.TAG_NAME }}.zip
          mv autograder/build/autograder_lab4.zip autograder_lab4_${{ env.TAG_NAME }}.zip
          mv autograder/build/autograder_lab5.zip autograder_lab5_${{ env.TAG_NAME }}.zip
          mv autograder/build/autograder_lab6.zip autograder_lab6_${{ env.TAG_NAME }}.zip
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          omitBody: True
          tag: ${{ env.TAG_NAME }}
          artifacts: |
            autograder_lab1_${{ env.TAG_NAME }}.zip
            autograder_lab2_${{ env.TAG_NAME }}.zip
            autograder_lab3_${{ env.TAG_NAME }}.zip
            autograder_lab4_${{ env.TAG_NAME }}.zip
            autograder_lab5_${{ env.TAG_NAME }}.zip
            autograder_lab6_${{ env.TAG_NAME }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
